### ISSUE TITLE
Swift 6 Compatibility and class property warning

### ISSUE THREAD

**Issue by adilrc** [PostHog/posthog-ios#127] opened 2024-04-12 07:46 UTC
### Problem Statement

I'm using your SDK with Xcode 15.3, and I'm getting a warning about a static property not being concurrency-safe. Can you please update the SDK to make it Swift 6 compatible and fix the warning?

Here's the warning I'm getting in _PostHogSDK.swift:54_:
`Class property 'shared' is not concurrency-safe because it is not either conforming to 'Sendable' or isolated to a global actor; this is an error in Swift 6`

Thanks!

**Comment by marandaneto** [comment] 2024-04-12 08:27
@adilrc thanks for reporting, did you change any configuration to get this warning? I am also using Xcode 15.3 but I don't get this warning.

**Comment by adilrc** [comment] 2024-04-12 09:14
Yes I do have [strict concurrency checks](https://www.swift.org/documentation/concurrency/) enabled in my package along with Swift 5.10. 

```swift
.target(
  ...
  swiftSettings: [
    .enableUpcomingFeature("StrictConcurrency")
  ]
)
```

**Comment by dehesa** [comment] 2024-04-12 17:52
I believe @adilrc  made a small typo. The SPM setting is:

```swift
.enableExperimentalFeature("StrictConcurrency"),
```

You can control the type of strict concurrency by following the attribute with `=` and then the level; i.e. `minimal`, `targeted`, `complete`. The absence of any mean `complete`. For example:

```
.enableExperimentalFeature("StrictConcurrency=targeted"),
```

If I may offer some advice in how to go about removing the concurrency warnings and making `PostHogSDK` safer:
- Ideally you would make `PostHogSDK` `Sendable`. This way the SDK can cross thread boundaries. I already see you are using locks when setting up some functions; therefore you could mark the whole class `PostHogSDK` as `@unchecked Sendable`. However, I think you are forwarding mutations on places unprotected by locks (e.g. `getDistinctId()` calls `isEnabled()` which relies in the _unprotected_ `enabled` private variable).
- Since making `PostHogSDK` sendable is probably too much work. You could mark the static `PostHog.shared` constant as `nonisolated(unsafe)`. This will remove the warning for users including the SDK as a static library while not making any _untrue_ promises to the compiler. By the way, you don't need the self-executing closure there.

```swift
public class PostHogSDK: NSObject {
  @objc public nonisolated(unsafe) static let shared = PostHogSDK(PostHogConfig(apiKey: ""))
}
```

**Comment by marandaneto** [comment] 2024-04-15 06:54
`enabled` is only mutated in the `setup` method which is manually locked with `setupLock` so it's not racing.
Reading `enabled` won't be an issue.

**Comment by marandaneto** [comment] 2024-04-15 12:08
Yep makes sense, I'm checking how to remove all the warnings without breaking changes, see [PR](https://github.com/PostHog/posthog-ios/pull/128).
At some point, we will migrate to Sendable everywhere + async-await approach but we need to be sure that back compatibility won't be a problem anymore, likely when dropping older versions of Swift.

**Comment by marandaneto** [comment] 2024-04-15 14:20
Hey @dehesa, good points.

The `@MainActor` annotations will be reverted, I wanted to get a feeling of how much work would be to fix (or silence) all the warnings in the SDK as well.
Some things will need to be marked as `@MainActor` but not for this patch, reasons are that some iOS classes are marked as `@MainActor`, for example, `UIDevice` and `UIScreen`, and they are used to enrich the events with device context.

I was not aware of the performance boost by marking them as `final`, thanks for sharing.

It's just a draft PR that I am using to learn more about the new strict concurrency since I have not played with it before, no intention to merge it as it is but thanks for calling it out.

**Comment by marandaneto** [comment] 2024-04-15 14:40
@dehesa the problem is that `nonisolated(unsafe)` is only available in Swift 5.10 right

**Comment by dehesa** [comment] 2024-04-15 15:02
You are correct! I believe you can do the following:

```swift
#if swift(>=5.10)
@objc public nonisolated(unsafe) static let shared = PostHogSDK(PostHogConfig(apiKey: ""))
#else
@objc public static let shared = PostHogSDK(PostHogConfig(apiKey: ""))
#endif
```

**Closed** 2024-04-16 06:49 UTC
Labels: enhancement

**Comment by dehesa** [comment] 2024-05-08 08:36
Hey @marandaneto. Any chance you can do a hotfix or minor release to remove the warning from our CI?
